#ifndef GENSERIAL_MODELINFO_AUTOGEN_H
#define GENSERIAL_MODELINFO_AUTOGEN_H

// DO NOT EDIT! This is an autogenerated file.

#include "macserial.h"

typedef enum {
  MacBook1_1, // Intel Core Duo T2400 @ 1.83 GHz
  MacBook10_1, // Intel Core m3-7Y32 @ 1.10 GHz
  MacBook2_1, // Intel Core 2 Duo T5600 @ 1.83 GHz
  MacBook3_1, // Intel Core 2 Duo T7500 @ 2.20 GHz
  MacBook4_1, // Intel Core 2 Duo T8300 @ 2.40 GHz
  MacBook5_1, // Intel Core 2 Duo P8600 @ 2.40 GHz
  MacBook5_2, // Intel Core 2 Duo P7450 @ 2.13 GHz
  MacBook6_1, // Intel Core 2 Duo P7550 @ 2.26 GHz
  MacBook7_1, // Intel Core 2 Duo P8600 @ 2.40 GHz
  MacBook8_1, // Intel Core M 5Y51 @ 1.10 GHz
  MacBook9_1, // Intel Core m3-6Y30 @ 1.10 GHz
  MacBookAir1_1, // Intel Core 2 Duo P7500 @ 1.60 GHz
  MacBookAir2_1, // Intel Core 2 Duo SL9600 @ 2.13 GHz
  MacBookAir3_1, // Intel Core 2 Duo SU9400 @ 1.40 GHz
  MacBookAir3_2, // Intel Core 2 Duo SL9400 @ 1.86 GHz
  MacBookAir4_1, // Intel Core i5-2467M @ 1.60 GHz
  MacBookAir4_2, // Intel Core i5-2557M @ 1.70 GHz
  MacBookAir5_1, // Intel Core i5-3317U @ 1.70 GHz
  MacBookAir5_2, // Intel Core i5-3317U @ 1.70GHz
  MacBookAir6_1, // Intel Core i5-4250U @ 1.30 GHz
  MacBookAir6_2, // Intel Core i5-4250U @ 1.30 GHz
  MacBookAir7_1, // Intel Core i5-5250U @ 1.60 GHz
  MacBookAir7_2, // Intel Core i5-5250U @ 1.60 GHz
  MacBookAir8_1, // Intel Core i5-8210Y @ 1.60 GHz
  MacBookPro1_1, // Intel Core Duo L2400 @ 1.66 GHz
  MacBookPro1_2, // Intel Core Duo T2600 @ 2.16 GHz
  MacBookPro10_1, // Intel Core i7-3615QM @ 2.30 GHz
  MacBookPro10_2, // Intel Core i5-3210M @ 2.50 GHz
  MacBookPro11_1, // Intel Core i5-4258U @ 2.40 GHz
  MacBookPro11_2, // Intel Core i7-4770HQ @ 2.20 GHz
  MacBookPro11_3, // Intel Core i7-4850HQ @ 2.30 GHz
  MacBookPro11_4, // Intel Core i7-4770HQ @ 2.20 GHz
  MacBookPro11_5, // Intel Core i7-4870HQ @ 2.50 GHz
  MacBookPro12_1, // Intel Core i5-5257U @ 2.70 GHz
  MacBookPro13_1, // Intel Core i5-6360U @ 2.00 GHz
  MacBookPro13_2, // Intel Core i7-6567U @ 3.30 GHz
  MacBookPro13_3, // Intel Core i7-6700HQ @ 2.60 GHz
  MacBookPro14_1, // Intel Core i5-7360U @ 2.30 GHz
  MacBookPro14_2, // Intel Core i5-7267U @ 3.10 GHz
  MacBookPro14_3, // Intel Core i7-7700HQ @ 2.80 GHz
  MacBookPro15_1, // Intel Core i7-8750H @ 2.20 GHz
  MacBookPro15_2, // Intel Core i7-8559U @ 2.70 GHz
  MacBookPro2_1, // Intel Core 2 Duo T7600 @ 2.33 GHz
  MacBookPro2_2, // Intel Core 2 Duo T7400 @ 2.16 GHz
  MacBookPro3_1, // Intel Core 2 Duo T7700 @ 2.40 GHz
  MacBookPro4_1, // Intel Core 2 Duo T8300 @ 2.40 GHz
  MacBookPro5_1, // Intel Core 2 Duo P8600 @ 2.40 GHz
  MacBookPro5_2, // Intel Core 2 Duo T9600 @ 2.80 GHz
  MacBookPro5_3, // Intel Core 2 Duo P8800 @ 2.66 GHz
  MacBookPro5_4, // Intel Core 2 Duo P8700 @ 2.53 GHz
  MacBookPro5_5, // Intel Core 2 Duo P7550 @ 2.26 GHz
  MacBookPro6_1, // Intel Core i5-540M @ 2.53 GHz
  MacBookPro6_2, // Intel Core i5-520M @ 2.40 GHz
  MacBookPro7_1, // Intel Core 2 Duo P8600 @ 2.40 GHz
  MacBookPro8_1, // Intel Core i5-2415M @ 2.30 GHz
  MacBookPro8_2, // Intel Core i7-2675QM @ 2.20 GHz
  MacBookPro8_3, // Intel Core i7-2820QM @ 2.30 GHz
  MacBookPro9_1, // Intel Core i7-3615QM @ 2.30 GHz
  MacBookPro9_2, // Intel Core i5-3210M @ 2.50 GHz
  MacPro1_1, // Intel Core Xeon 5130 x2 @ 2.00 GHz
  MacPro2_1, // Intel Xeon X5365 x2 @ 3.00 GHz
  MacPro3_1, // Intel Xeon E5462 x2 @ 2.80 GHz
  MacPro4_1, // Intel Xeon W3520 @ 2.66 GHz
  MacPro5_1, // Intel Xeon W3530 @ 2.80 GHz
  MacPro6_1, // Intel Xeon E5-1620 v2 @ 3.70 GHz
  Macmini1_1, // Intel Core Solo T1200 @ 1.50 GHz
  Macmini2_1, // Intel Core 2 Duo T5600 @ 1.83 GHz
  Macmini3_1, // Intel Core 2 Duo P7350 @ 2.00 GHz
  Macmini4_1, // Intel Core 2 Duo P8600 @ 2.40 GHz
  Macmini5_1, // Intel Core i5-2415M @ 2.30 GHz
  Macmini5_2, // Intel Core i5-2520M @ 2.50 GHz
  Macmini5_3, // Intel Core i7-2635QM @ 2.00 GHz
  Macmini6_1, // Intel Core i5-3210M @ 2.50 GHz
  Macmini6_2, // Intel Core i7-3615QM @ 2.30 GHz
  Macmini7_1, // Intel Core i5-4260U @ 1.40 GHz
  Macmini8_1, // Intel Core i7-8700B @ 3.20 GHz
  Xserve1_1, // Intel Xeon 5130 x2 @ 2.00 GHz
  Xserve2_1, // Intel Xeon E5462 x2 @ 2.80 GHz
  Xserve3_1, // Intel Xeon E5520 x2 @ 2.26 GHz
  iMac10_1, // Intel Core 2 Duo E7600 @ 3.06 GHz
  iMac11_1, // Intel Core i5-750 @ 2.66 GHz
  iMac11_2, // Intel Core i3-540 @ 3.06 GHz
  iMac11_3, // Intel Core i5-760 @ 2.80 GHz
  iMac12_1, // Intel Core i5-2400S @ 2.50 GHz
  iMac12_2, // Intel Core i7-2600 @ 3.40 GHz
  iMac13_1, // Intel Core i7-3770S @ 3.10 GHz
  iMac13_2, // Intel Core i5-3470S @ 2.90 GHz
  iMac13_3, // Intel Core i5-3470S @ 2.90 GHz
  iMac14_1, // Intel Core i5-4570R @ 2.70 GHz
  iMac14_2, // Intel Core i7-4771 @ 3.50 GHz
  iMac14_3, // Intel Core i5-4570S @ 2.90 GHz
  iMac14_4, // Intel Core i5-4260U @ 1.40 GHz
  iMac15_1, // Intel Core i7-4790k @ 4.00 GHz
  iMac16_1, // Intel Core i5-5250U @ 1.60 GHz
  iMac16_2, // Intel Core i5-5675R @ 3.10 GHz
  iMac17_1, // Intel Core i5-6500 @ 3.20 GHz
  iMac18_1, // Intel Core i5-7360U @ 2.30 GHz
  iMac18_2, // Intel Core i5-7400 @ 3.00 GHz
  iMac18_3, // Intel Core i5-7600k @ 3.80 GHz
  iMac19_1, // Intel Core i9-9900K @ 3.60 GHz
  iMac19_2, // Intel Core i5-8500 @ 3.00 GHz
  iMac4_1, // Intel Core Duo T2400 @ 1.83 GHz
  iMac4_2, // Intel Core Duo T2400 @ 1.83 GHz
  iMac5_1, // Intel Core 2 Duo T7200 @ 2.00 GHz
  iMac5_2, // Intel Core 2 Duo T5600 @ 1.83 GHz
  iMac6_1, // Intel Core 2 Duo T7400 @ 2.16 GHz
  iMac7_1, // Intel Core 2 Duo T7300 @ 2.00 GHz
  iMac8_1, // Intel Core 2 Duo E8435 @ 3.06 GHz
  iMac9_1, // Intel Core 2 Duo E8135 @ 2.66 GHz
  iMacPro1_1, // Intel Xeon W-2140B CPU @ 3.20 GHz
} AppleModel;

#define APPLE_MODEL_MAX 110

static PLATFORMDATA ApplePlatformData[] = {
  { "MacBook1,1", "W80A041AU9B" },
  { "MacBook10,1", "C02TQHACHH27" },
  { "MacBook2,1", "W88A041AWGP" },
  { "MacBook3,1", "W8747HACZ66" },
  { "MacBook4,1", "W88A041A0P0" },
  { "MacBook5,1", "W8944T1S1AQ" },
  { "MacBook5,2", "W88AAAAA9GU" },
  { "MacBook6,1", "451131JCGAY" },
  { "MacBook7,1", "451211MEF5X" },
  { "MacBook8,1", "C02RCE58GCN3" },
  { "MacBook9,1", "C02RM408HDNK" },
  { "MacBookAir1,1", "W864947A18X" },
  { "MacBookAir2,1", "W86494769A7" },
  { "MacBookAir3,1", "C02FLHACD0QX" },
  { "MacBookAir3,2", "C02DRHACDDR3" },
  { "MacBookAir4,1", "C02KGHACDRV9" },
  { "MacBookAir4,2", "C02GLHACDJWT" },
  { "MacBookAir5,1", "C02J6HACDRV6" },
  { "MacBookAir5,2", "C02HRJXWDRVC" },
  { "MacBookAir6,1", "C02KTHACF5NT" },
  { "MacBookAir6,2", "C02HACKUF5V7" },
  { "MacBookAir7,1", "C02PCLGFH569" },
  { "MacBookAir7,2", "C02Q1HACG940" },
  { "MacBookAir8,1", "C02XG1D8JK78" },
  { "MacBookPro1,1", "W884857JVJ1" },
  { "MacBookPro1,2", "W8629HACTHY" },
  { "MacBookPro10,1", "C02J40Y8F51R" },
  { "MacBookPro10,2", "C02JJ70ADR53" },
  { "MacBookPro11,1", "C02LSHACFH00" },
  { "MacBookPro11,2", "C02LSHACG86R" },
  { "MacBookPro11,3", "C02LSHACFR1M" },
  { "MacBookPro11,4", "C02SNHACG8WN" },
  { "MacBookPro11,5", "C02LSHACG85Y" },
  { "MacBookPro12,1", "C02Q51OSH1DP" },
  { "MacBookPro13,1", "C17SJ18EGVC1" },
  { "MacBookPro13,2", "C02SLHACGYFH" },
  { "MacBookPro13,3", "C02T6L42GTFL" },
  { "MacBookPro14,1", "C02TNHACHV29" },
  { "MacBookPro14,2", "C02TQHACHV2N" },
  { "MacBookPro14,3", "C02TQHACHTD5" },
  { "MacBookPro15,1", "C02X846JJG5J" },
  { "MacBookPro15,2", "C02X141CJHCC" },
  { "MacBookPro2,1", "W88130WUW0H" },
  { "MacBookPro2,2", "W8827B4CW0L" },
  { "MacBookPro3,1", "W8841OHZX91" },
  { "MacBookPro4,1", "W88484F2YP4" },
  { "MacBookPro5,1", "W88439FE1G0" },
  { "MacBookPro5,2", "W8908HAC2QP" },
  { "MacBookPro5,3", "W8035TG97XK" },
  { "MacBookPro5,4", "W8948HAC7XJ" },
  { "MacBookPro5,5", "W8035TG966D" },
  { "MacBookPro6,1", "C02G5834DC79" },
  { "MacBookPro6,2", "CK132A91AGW" },
  { "MacBookPro7,1", "CK145C7NATM" },
  { "MacBookPro8,1", "W89F9196DH2G" },
  { "MacBookPro8,2", "C02HL0FGDF8X" },
  { "MacBookPro8,3", "W88F9CDEDF93" },
  { "MacBookPro9,1", "C02LW984F1G4" },
  { "MacBookPro9,2", "C02HA041DTY3" },
  { "MacPro1,1", "W88A7HACUQ2" },
  { "MacPro2,1", "W8930518UPZ" },
  { "MacPro3,1", "W88A77AA5J4" },
  { "MacPro4,1", "CT942NZP20H" },
  { "MacPro5,1", "H02380NSEUH" },
  { "MacPro6,1", "F5KLA770F9VM" },
  { "Macmini1,1", "W8702N1JU35" },
  { "Macmini2,1", "W8705W9LYL2" },
  { "Macmini3,1", "W8905BBE19X" },
  { "Macmini4,1", "C02FHBBEDD6H" },
  { "Macmini5,1", "C07GA041DJD0" },
  { "Macmini5,2", "C07HVHACDJD1" },
  { "Macmini5,3", "C07GWHACDKDJ" },
  { "Macmini6,1", "C07JNHACDY3H" },
  { "Macmini6,2", "C07JD041DWYN" },
  { "Macmini7,1", "C02NN7NHG1J0" },
  { "Macmini8,1", "C07XL9WEJYVX" },
  { "Xserve1,1", "CK703E1EV2Q" },
  { "Xserve2,1", "CK830DLQX8S" },
  { "Xserve3,1", "CK933YJ16HS" },
  { "iMac10,1", "W80AA98A5PE" },
  { "iMac11,1", "G8942B1V5PJ" },
  { "iMac11,2", "W8034342DB7" },
  { "iMac11,3", "QP0312PBDNR" },
  { "iMac12,1", "W80CF65ADHJF" },
  { "iMac12,2", "W88GG136DHJQ" },
  { "iMac13,1", "C02JA041DNCT" },
  { "iMac13,2", "C02JB041DNCW" },
  { "iMac13,3", "C02KVHACFFYW" },
  { "iMac14,1", "D25LHACKF8J2" },
  { "iMac14,2", "D25LHACKF8JC" },
  { "iMac14,3", "D25LHACKF8J3" },
  { "iMac14,4", "D25LHACKFY0T" },
  { "iMac15,1", "C02Q6HACFY10" },
  { "iMac16,1", "C02QQHACGF1J" },
  { "iMac16,2", "C02PNHACGG7G" },
  { "iMac17,1", "C02QFHACGG7L" },
  { "iMac18,1", "C02TDHACH7JY" },
  { "iMac18,2", "C02TDHACJ1G5" },
  { "iMac18,3", "C02TDHACJ1GJ" },
  { "iMac19,1", "C02Y90H3JV3Q" },
  { "iMac19,2", "C02Y93YXJWDX" },
  { "iMac4,1", "W8608HACU2P" },
  { "iMac4,2", "W8627HACV2H" },
  { "iMac5,1", "CK637HACX1A" },
  { "iMac5,2", "W8716HACWH5" },
  { "iMac6,1", "W8652HACVGN" },
  { "iMac7,1", "W8741HACX87" },
  { "iMac8,1", "W8755HAC2E2" },
  { "iMac9,1", "W89A00A36MJ" },
  { "iMacPro1,1", "C02VV5RFHX87" },
};

#define APPLE_MODEL_CODE_MAX 53
static const char *AppleModelCode[][APPLE_MODEL_CODE_MAX] = {
  /* MacBook1,1     */ {"U9B"},
  /* MacBook10,1    */ {"HH27", "HH25"},
  /* MacBook2,1     */ {"WGP"},
  /* MacBook3,1     */ {"Z66"},
  /* MacBook4,1     */ {"0P0"},
  /* MacBook5,1     */ {"1AQ"},
  /* MacBook5,2     */ {"9GU"},
  /* MacBook6,1     */ {"GAY"},
  /* MacBook7,1     */ {"F5X"},
  /* MacBook8,1     */ {"GCN3", "DNCR", "DNCT", "DNML", "DNMM", "F8QM", "F8QN", "F9RN", "FC6M", "FC6N", "FC6P", "FD55", "FD5Y", "FF7L", "FFVW", "FFVY", "FG46", "FGC4", "FGMR", "FGMT", "FL8N", "FM8L", "FM8M", "FM8N", "FMLG", "FP12"},
  /* MacBook9,1     */ {"HDNK", "GTHR", "GTHT", "GTHV", "GTHW", "GTHX", "GTHY", "GTJ0", "GTJ1", "GTJ2", "GTJ3", "GTJ4", "GTJ6", "GTJ7", "GTJ8", "GTJ9", "GTJC", "GTJD", "H3QW", "H3QX", "H3QY", "H3R5", "H3R6", "H3R7"},
  /* MacBookAir1,1  */ {"18X"},
  /* MacBookAir2,1  */ {"9A7"},
  /* MacBookAir3,1  */ {"D0QX", "DDQW"},
  /* MacBookAir3,2  */ {"DDR3", "DDR1"},
  /* MacBookAir4,1  */ {"DRV9", "DJY8", "DJY9", "DJYC", "DJYD", "DRHF", "DRKH", "DTJW", "DTJY", "DTK1", "DTK2", "DW1C", "DW4J", "DWWM", "DWWN", "DY2M", "F2JP"},
  /* MacBookAir4,2  */ {"DJWT", "DJWQ", "DJWR", "DJWV", "DRKG", "DRQ4", "DTJT", "DTJV", "DTK0", "DW1N", "DW4H", "F14R", "F14V", "F2JQ", "F75Y"},
  /* MacBookAir5,1  */ {"DRV6", "DRV7", "DRV8", "DRV9", "F569", "F56C", "F56G", "F57H", "F5MV", "F67D", "F67F", "F67K", "F67L", "F67M", "F88G", "F88K", "F88V", "F910"},
  /* MacBookAir5,2  */ {"DRVC", "DRVD", "DRVF", "DRVG", "F2FV", "F56D", "F56F", "F56H", "F56J", "F57J", "F5MW", "F67G", "F67H", "F67J", "F67P", "F6TN", "F760", "F90Y"},
  /* MacBookAir6,1  */ {"F5NT", "F5N7", "F5N8", "F5YV", "F5YW", "FH51", "FH52", "FKYN", "FKYP", "FLCF", "FMR5", "FMR6", "FMR9", "FMRC", "FMRD", "FMRF", "FMRG", "FMRM", "FMRN", "FN5M", "FN7F", "FP2N", "FP3C", "FQLG", "FT30", "FM72", "G083", "G084", "G2CF", "G2GH", "G2GJ", "G2PY", "G2Q0", "G4FY", "G4H0", "G4H4", "G4HK", "G4HM", "G58J", "G5RK", "G5RL", "G5RM", "G6D3", "GP4N", "GP4P"},
  /* MacBookAir6,2  */ {"F5V7", "F5V8", "F6T5", "F6T6", "FH53", "FKYQ", "FKYR", "FLCG", "FM23", "FM3Y", "FM74", "FMR7", "FMR8", "FMRH", "FMRJ", "FMRK", "FMRL", "FMRV", "FMRW", "FMRY", "FN3Y", "FN40", "FN7G", "FP2P", "FQL9", "FQLC", "FQLD", "FQLF", "G6PM", "G085", "G086", "G2CC", "G2CD", "G2GK", "G2GL", "G2GM", "G2GN", "G356", "G4H1", "G4H2", "G4H3", "G4HN", "G4HP", "G58K", "G5RN", "G5RP", "G5RQ", "G6D4", "G6D5", "G829", "G8J1", "GP4L", "GP4M"},
  /* MacBookAir7,1  */ {"H569", "GFWK", "GFWL", "GFWM", "GFWN", "GFWP", "GKJY", "GKK0", "GL28", "GL2D", "GL2F", "GL2H", "GLCQ", "GMC5", "GMC6", "GMC7", "GMC8", "GMC9", "GNJK", "GNJL"},
  /* MacBookAir7,2  */ {"G940", "G941", "G942", "G943", "G944", "GKJT", "GKJV", "GLCN", "GLCP", "GM14", "GM15", "GM38", "GM9G", "GMC3", "GN8C", "GNJJ", "H3QD", "H3QF", "H3QJ", "H3QK", "H569"},
  /* MacBookAir8,1  */ {"JK77", "JK77", "JK7C", "JK7D", "JK7F", "JK7G", "JK7L", "JK7M", "JK7P", "JK7Q", "JK7R", "JK7T"},
  /* MacBookPro1,1  */ {"VJ1"},
  /* MacBookPro1,2  */ {"THY"},
  /* MacBookPro10,1 */ {"DKQ1", "DKQ2", "DKQ4", "DKQ5", "F51R", "F5Y2", "F69W", "F69Y", "F6DN", "F6F3", "F6L9", "F8JY", "F96W", "F9F1", "F9F2", "FCQ3", "FFT0", "FFT1", "FFT2", "FFT3", "FFT4", "FG1H", "FG1J", "FGFH", "FGFJ", "FGFK", "FGFL", "FGN7", "FGWF", "FGWG", "FGWH", "FHCQ", "FHCR", "FJ47", "FJVJ", "FL94", "FR8D"},
  /* MacBookPro10,2 */ {"G4N7", "DR53", "DR54", "DR55", "DR56", "F775", "F776", "F7YF", "F897", "F8V6", "F8V7", "F8V8", "F9JT", "F9V1", "F9VQ", "FG7Q", "FG7R", "FL85", "FMLJ", "FFRP", "FFRR", "FG1F", "FG28", "FGM8", "FGN5", "FGN6", "FGPJ", "FHCH", "FHN0"},
  /* MacBookPro11,1 */ {"FH00", "FGYY", "FH01", "FH02", "FH03", "FH04", "FH05", "FRF6", "FRF7", "FRQF", "FT4Q", "FT4R", "FT4T", "FT4V", "FTC9", "FTCD", "FTCH", "FTCK", "FTCL", "FTPH", "FTPJ", "FTPK", "FTT4", "FVVW", "FVWQ", "G3QJ", "G3QK", "G4N6", "G4N7", "G3QQ", "G3QR"},
  /* MacBookPro11,2 */ {"G86R", "FD56", "G3QC", "G3QG", "G3QN"},
  /* MacBookPro11,3 */ {"FR1M", "FD57", "FD59", "G3QP", "FTPY"},
  /* MacBookPro11,4 */ {"G8WN", "G8WL"},
  /* MacBookPro11,5 */ {"G85Y", "G3QD", "G8WM", "G8WP", "G8WQ", "GQCT"},
  /* MacBookPro12,1 */ {"H1DP", "FVH3", "FVH4", "FVH5", "FVH6", "FVH7", "FVH8", "FVH9", "GKJG", "GKJM", "GKJN", "GL36", "GL37", "GM0V", "GM0W", "GM10", "GM11", "GM12", "GM13", "GQR4", "GQR5", "GQR6", "H1DQ"},
  /* MacBookPro13,1 */ {"GVC1", "GVC8", "GY25", "GY6N", "HV5M", "HV5H", "HV5J", "HV5K", "HV5L", "HV5G", "HV5D", "HV5N", "HWCH", "HYP5"},
  /* MacBookPro13,2 */ {"GYFH", "GTDX", "GTFJ", "GYGR", "HF1R", "HF1P", "HF1Q", "HF1T", "HP49", "HP4D", "HWH2", "HXD5"},
  /* MacBookPro13,3 */ {"GTFN", "GTDY", "GTF1", "GTFL", "GTFM", "H03M", "H03Q", "H03T", "H03Y", "H040", "HXF8"},
  /* MacBookPro14,1 */ {"HV29", "HV22", "HV2F", "HV2J"},
  /* MacBookPro14,2 */ {"HV2N", "HV2M", "HV2R"},
  /* MacBookPro14,3 */ {"HTD5", "HTD6", "HTD8", "HTD9", "HTDF", "HTDH", "HTDD"},
  /* MacBookPro15,1 */ {"KGYG", "JG5H", "JG5J", "JG5K", "JG5L", "JG5M", "JGH5", "JGH6", "JGH7", "JGH8", "KGYF", "KGYH", "KQ9Q", "KQ9R", "KQ9T", "KQ9V", "KQ9W", "KQ9X", "KQ9Y", "KQC0", "KQC1", "KQC2", "KQC3", "KQC4", "KQC5", "KQC6", "KQC7", "KQC8", "KQC9", "KQCC", "KQCD", "KQCF", "KQCG", "KQCH", "KQCJ", "KQCK", "KQCL", "KQCM", "KQCN", "KQCP", "KQCR", "KQCT", "KQCV", "KQCW", "KQCX", "KWJ2"},
  /* MacBookPro15,2 */ {"JHCC", "JHC8", "JHC9", "JHCD", "JHCF", "JHD2", "JHD3", "JHD4", "JHD5", "KK98", "KK99", "KK9C", "KQ1X", "KQ1Y", "KQ20", "KQ21", "KQ22", "KQ23", "KQ24", "KQ25", "KQ26", "KQ27"},
  /* MacBookPro2,1  */ {"W0H"},
  /* MacBookPro2,2  */ {"W0L"},
  /* MacBookPro3,1  */ {"X91"},
  /* MacBookPro4,1  */ {"YP4"},
  /* MacBookPro5,1  */ {"1G0"},
  /* MacBookPro5,2  */ {"2QP"},
  /* MacBookPro5,3  */ {"7XK"},
  /* MacBookPro5,4  */ {"7XJ"},
  /* MacBookPro5,5  */ {"66D", "66E"},
  /* MacBookPro6,1  */ {"DC79"},
  /* MacBookPro6,2  */ {"AGW"},
  /* MacBookPro7,1  */ {"ATM", "ATP"},
  /* MacBookPro8,1  */ {"DH2G", "DH2L", "DV13", "DH2H"},
  /* MacBookPro8,2  */ {"DF8X", "DRJD", "DRJF", "DF8V", "DRJC"},
  /* MacBookPro8,3  */ {"DF93", "DW48", "DMGH"},
  /* MacBookPro9,1  */ {"F1G4", "F1G3", "DV33"},
  /* MacBookPro9,2  */ {"DTY3", "DV30", "F5WW"},
  /* MacPro1,1      */ {"UPZ"},
  /* MacPro2,1      */ {"UPZ"},
  /* MacPro3,1      */ {"5J4", "XYK", "XYL", "1Z9"},
  /* MacPro4,1      */ {"20H", "BXD"},
  /* MacPro5,1      */ {"EUH", "GWR", "HFC", "HFA", "HFD", "HFF", "HFG", "HFJ", "HFK", "HFL", "HFN", "EUF", "F4MG", "F4MH"},
  /* MacPro6,1      */ {"F9VM", "F693", "F694", "F9VN", "FRDW", "FRDY", "FRF0", "FRF1", "FRF2", "FRF3", "FRF4", "FRF5", "FRQC", "FT3F", "FT3G", "FT3H", "FT95", "FT96", "FT97", "FT98", "FT99", "FT9C", "FT9D", "FY3Y", "FY40", "G1LJ", "G1LK", "G1LL", "G1LM", "G1LN", "G1LP", "G1LQ", "G1LR", "G1LT", "G1LV", "G1LW", "G1LY", "G1M0", "G1M1", "G8GC", "G8GD"},
  /* Macmini1,1     */ {"U35"},
  /* Macmini2,1     */ {"YL2"},
  /* Macmini3,1     */ {"19X"},
  /* Macmini4,1     */ {"DD6H"},
  /* Macmini5,1     */ {"DJD0", "DJD1", "DJD2", "DJD3", "DRHT", "DTCJ", "DTCK", "DTCM", "DW33", "DW34", "DW35", "DW36", "DW37", "DW38", "DW3C", "DYQJ"},
  /* Macmini5,2     */ {"DJD1", "DJD0", "DJD2", "DJD3", "DRHT", "DTCJ", "DTCK", "DTCM", "DW33", "DW34", "DW35", "DW36", "DW37", "DW38", "DW3C", "DYQJ"},
  /* Macmini5,3     */ {"DKDJ", "DJY7", "DRHR", "DTCL", "DTCT", "DTCV", "DW39", "DW3D"},
  /* Macmini6,1     */ {"DY3H", "DWYL", "DWYM", "DY3G", "F9RK", "F9RL", "F9RM", "F9VV", "F9VW", "F9W0", "F9W1", "F9W2", "FD9G", "FD9H", "FD9J", "FD9K", "FDWK", "FGML", "FRFP", "FW56", "FW57", "G430"},
  /* Macmini6,2     */ {"DWYN", "DWYL", "DWYM", "DY3G", "DY3H", "F9RK", "F9RL", "F9RM", "F9VV", "F9VW", "F9W0", "F9W1", "F9W2", "FD9G", "FD9H", "FD9J", "FD9K", "FDWK", "FGML", "FRFP", "FW56", "FW57", "G430", "DWYN", "DY3J", "F9VY", "F9W3", "FC08", "FCCW", "FP14", "FP39"},
  /* Macmini7,1     */ {"G1J0", "G1HV", "G1HW", "G1HY", "G1J1", "G1J2", "GCVG", "GCVH", "GCVJ", "GCVN", "GCVP", "GCVQ", "GCVV", "GCVW", "GCVY", "GCW0", "GCW1", "GF1N", "GF1Q", "GF1T", "GJDC"},
  /* Macmini8,1     */ {"JYVX", "JYVW", "JYVY", "JYW0"},
  /* Xserve1,1      */ {"V2Q"},
  /* Xserve2,1      */ {"X8S"},
  /* Xserve3,1      */ {"6HS"},
  /* iMac10,1       */ {"5PE"},
  /* iMac11,1       */ {"5PJ", "5RU"},
  /* iMac11,2       */ {"DB7"},
  /* iMac11,3       */ {"DNR", "DB6"},
  /* iMac12,1       */ {"DHJF"},
  /* iMac12,2       */ {"DHJQ", "DHJP", "DHJW"},
  /* iMac13,1       */ {"DNCT", "DNCR", "DNML", "DNMM", "F8QM", "F8QN", "F9RN", "FC6M", "FC6N", "FC6P", "FD55", "FD5Y", "FF7L"},
  /* iMac13,2       */ {"DNCW", "DNCV", "DNMN", "DNMP", "F29N", "F8QP", "F8QQ", "FD5T", "FD5V", "FFM8", "FFM9", "FFMC", "FFMD", "FFMF", "FFMG", "FFMJ", "FFMK", "FFML", "FFMM", "FFMN", "FFW0", "FFW1", "FG47", "FGMW", "FGMY", "FGRP", "FL8M", "FM8P", "FM8Q", "FMLH", "FP13", "FP62", "FTQ5"},
  /* iMac13,3       */ {"FFYW", "FFYV", "FGPL", "FGPM", "FJQQ", "FLMH"},
  /* iMac14,1       */ {"F8J2", "F8J7", "FPF1", "FQMV"},
  /* iMac14,2       */ {"F8JC", "F8J4", "F8J5", "F8J9", "FLHH", "FPDY", "FPF0", "FPF3", "FPF4", "FQPG", "FQPH", "FQPJ", "FQPK", "FQPL", "FQPM", "FQPN", "FQPP", "FR20", "FR22", "FR2W", "FRM9", "FT4N", "FWQ5", "FWQ6", "FWQ7", "FWQ8", "FY15", "FY9D", "FY9F", "G6DP", "GHFF"},
  /* iMac14,3       */ {"F8J3", "F8J8", "FPDW"},
  /* iMac14,4       */ {"FY0T", "FY0V", "FY65", "FY69", "G56J", "G56K", "G5W4", "G5W5", "G5W6", "G8L2"},
  /* iMac15,1       */ {"FY10", "FY11", "FY14", "FY68", "FY6F", "GCTM", "GDQY", "GDR3", "GDR4", "GDR5", "GDR6", "GDR7", "GDR8", "GDR9", "GDRC", "GFFQ", "GJDM", "GJDN", "GJDP", "GJDQ", "FY10", "FY13", "FY6D", "GL1Q", "GL1R", "GL1T", "GL1V", "GL1W"},
  /* iMac16,1       */ {"GF1J"},
  /* iMac16,2       */ {"GG7G", "GG78", "GG7F", "GG7H", "H0P7", "H1F3", "H1F5", "H1F7", "H1F8", "H1F9", "H25N", "H8L0", "H8L1", "H8L2", "H8L3"},
  /* iMac17,1       */ {"GG7L", "GG7J", "GG7N", "GG7R", "GG7T", "GG7V", "GG80", "GG81", "GG82", "GQ17", "GQ18", "H0Q3", "H0Q4", "H0Q5", "H3GP", "H3GQ", "H3GR", "H3GT", "H3GV", "H3GW", "H8L5", "H8L6"},
  /* iMac18,1       */ {"H7JY", "H7VF"},
  /* iMac18,2       */ {"J1G5"},
  /* iMac18,3       */ {"J1GJ", "J1GQ", "J1GG"},
  /* iMac19,1       */ {"JV3Q", "JV3P", "J1GG", "JV40"},
  /* iMac19,2       */ {"JWDW", "JWDX"},
  /* iMac4,1        */ {"U2P"},
  /* iMac4,2        */ {"V2H"},
  /* iMac5,1        */ {"X1A"},
  /* iMac5,2        */ {"WH5"},
  /* iMac6,1        */ {"VGN"},
  /* iMac7,1        */ {"X87"},
  /* iMac8,1        */ {"2E2"},
  /* iMac9,1        */ {"6MJ"},
  /* iMacPro1,1     */ {"HX87", "HX8F", "JL53", "JL54", "JL55", "JLCN", "JLCP", "JLCR", "JLCT", "JLCV", "JLCW", "JLCX", "JLCY", "JLD0", "JLD1", "JLD2"},
};

#define APPLE_BOARD_CODE_MAX 128
static const char *AppleBoardCode[][APPLE_BOARD_CODE_MAX] = {
  /* MacBook1,1     */ {"V3G", "VZ0", "TYU", "VZ1", "VMC", "VZ2", "WXS", "WXW", "X0W", "X10", "WXR", "WXV", "X0V", "X0Y", "WXT", "WXU", "X0X", "X0Z"},
  /* MacBook10,1    */ {"HJ9L", "HJ9M", "HJ9N", "HJ9P", "HJ9W", "HJ9X", "HJ9Y", "HJC0", "HJC5", "HJC6", "HJC7", "HJC8", "HJ9G", "HJ9H", "HJ9J", "HJ9K", "HJ9Q", "HJ9R", "HJ9T", "HJ9V", "HJC1", "HJC2", "HJC3", "HJC4", "HJCL", "HJCM", "HJCN", "HJCP", "HJD5", "HJD6", "HJD7", "HJD8", "HJDQ", "HJDR", "HJDT", "HJDV", "HJCQ", "HJCR", "HJCT", "HJCV", "HJD9", "HJDC", "HJDD", "HJDF", "HJDW", "HJDX", "HJDY", "HJF0", "HJC9", "HJCC", "HJCD", "HJCF", "HJCW", "HJCX", "HJCY", "HJD0", "HJDG", "HJDH", "HJDJ", "HJDK", "HJCG", "HJCH", "HJCJ", "HJCK", "HJD1", "HJD2", "HJD3", "HJD4", "HJDL", "HJDM", "HJDN", "HJDP", "HJF9", "HJFC", "HJFD", "HJFF", "HJFW", "HJFX", "HJFY", "HJG0", "HJGG", "HJGH", "HJGJ", "HJGK", "HJFG", "HJFH", "HJFJ", "HJFK", "HJG1", "HJG2", "HJG3", "HJG4", "HJGL", "HJGM", "HJGN", "HJGP", "HJF1", "HJF2", "HJF3", "HJF4", "HJFL", "HJFM", "HJFN", "HJFP", "HJG5", "HJG6", "HJG7", "HJG8", "HJF5", "HJF6", "HJF7", "HJF8", "HJFQ", "HJFR", "HJFT", "HJFV", "HJG9", "HJGC", "HJGD", "HJGF"},
  /* MacBook2,1     */ {"WES", "WEV", "W6V", "WET", "WEU", "WEW"},
  /* MacBook3,1     */ {""},
  /* MacBook4,1     */ {""},
  /* MacBook5,1     */ {""},
  /* MacBook5,2     */ {""},
  /* MacBook6,1     */ {""},
  /* MacBook7,1     */ {""},
  /* MacBook8,1     */ {"FV36", "FV3T", "FV5W", "FV9F", "FV6W", "FVC7", "FVF6", "FV87", "FV5H", "FVF0", "FV7P", "FVC8"},
  /* MacBook9,1     */ {"FV48", "FV8P", "FV9C", "FV9Q", "H6LL", "H6LM", "H6LN", "H6LP", "FV3K", "FV5M", "FV67", "FV77", "H6LQ", "H6LR", "H6LT", "H6LV", "FV3D", "FV4C", "FV9K", "FVC6", "H6M1", "H6M2", "H6M3", "H6M4", "FV89", "FV8Q", "FV8T", "FVCP", "H6M5", "H6M6", "H6M7", "H6M8"},
  /* MacBookAir1,1  */ {""},
  /* MacBookAir2,1  */ {""},
  /* MacBookAir3,1  */ {"DF83", "DF8D", "DF8G", "DF8L", "DG4L", "DG4M", "DF86", "DF8F", "DF8H", "DF8M", "DG4H", "DG4K", "DD0T", "DD14", "DD15", "DG4G", "DG4Q", "DD0Q", "DD0R", "DD0V", "DD12", "DG4T", "DG4V"},
  /* MacBookAir3,2  */ {"DCWQ", "DCX3", "DCXM", "DCXW", "DG4W", "DG4Y", "DCX7", "DCXP", "DCXQ", "DCXV", "DCWT", "DCWW", "DCX5", "DCXJ", "DG51", "DG52", "DCWV", "DCWX", "DCX4", "DCXF"},
  /* MacBookAir4,1  */ {"DK9L", "DLCP", "DLCT", "DY58", "DY5D", "DY5F", "DLCR", "DLD1", "DLD6", "DY59", "DY5C", "DY5G"},
  /* MacBookAir4,2  */ {"DP1G", "DP1J", "DP1P", "DY4Q", "DY4W", "DY4Y", "DP1H", "DP1K", "DP1L", "DY4J", "DY4M", "DY4R"},
  /* MacBookAir5,1  */ {"DYKF", "DYKK", "F27J", "F9DH", "DYKG", "F0V4", "F27D", "F9DK", "F27G", "F27H", "F27K", "F9DG", "F279", "F27C", "F27F", "F9DJ"},
  /* MacBookAir5,2  */ {"F25Q", "F25Y", "F27Y", "F9DF", "F25P", "F25T", "F27Q", "F9D8", "F25N", "F25R", "F27T", "F9D7", "F25V", "F25W", "F27R", "F9D9"},
  /* MacBookAir6,1  */ {"FD09", "FD0C", "FD08", "FD0D", "FY44", "FY47", "G3MT", "G8JP", "FY46", "FY48", "G3MY", "G8JM", "F6V4", "F9Q1", "G3MW", "G8JN", "F9Q2", "F9Q3", "G3MV", "G8JQ"},
  /* MacBookAir6,2  */ {"FD47", "FD49", "FD48", "FD4C", "FY58", "FY5C", "G3N3", "G8JR", "FY56", "FY57", "G3N4", "G8JV", "FHDQ", "FHDV", "G3N5", "G8JT", "FHDT", "FHDW", "G3N2", "G8JW"},
  /* MacBookAir7,1  */ {"G90F", "G90R", "G90V", "G909", "G90J", "G90K", "G90G", "G90M", "G90W", "G90Q", "G90Y", "G910"},
  /* MacBookAir7,2  */ {"G91Q", "G91T", "G91Y", "G925", "G928", "G92C", "G922", "G929", "G92F", "G91R", "G926", "G92G"},
  /* MacBookAir8,1  */ {"KN2R", "KN7H", "KN7V", "KN86", "KN8M", "KN34", "KN3J", "KN3Y", "KMXD", "KMXQ", "KMY4", "KMYH", "KNDX", "KNF8", "KN9P", "KNC2", "KNCF", "KNCR", "KN5C", "KN5P", "KN62", "KN6F", "KN0L", "KN0Y", "KN19", "KN1N", "KNGC"},
  /* MacBookPro1,1  */ {""},
  /* MacBookPro1,2  */ {""},
  /* MacBookPro10,1 */ {"DY3V", "DY3W", "DY3Y", "DY40", "DY41", "DY42", "DY43", "DY44", "DY45", "DY4C", "F78Q", "F78Y", "F790", "DYJ5", "DYJ6", "DRDN", "DRDP", "DRDW", "DRF0", "DRF1", "DRF4", "DT9D", "DT9F", "DT9G", "DT9H", "F78N", "F78P", "DRDQ", "DRDT", "DYW4", "DYW5", "F0HM", "F0HN", "F0HR", "F0HT", "F0HV", "F0HY", "F0J3", "F0JD", "F78T", "F791", "F0JC", "FF63", "FF65", "FF67", "FF6W", "FF70", "FF72", "FF74", "FF69", "FF6D", "FF6G", "FF6J", "FF6L", "FF6N", "FF6Q", "FF6T", "FFW6", "FFW7", "FFWG", "FFWJ", "FFWK", "FFWM", "FFWN", "FFWP", "FFW8", "FFW9", "FFWC", "FFWD", "FFWF", "FFWH", "FFWL", "FFWQ", "FF64", "FF66", "FF68", "FF6F", "FF6Y", "FF71", "FF73", "FF75", "FF6C", "FF6H", "FF6K", "FF6M", "FF6P", "FF6R", "FF6V", "FF7M"},
  /* MacBookPro10,2 */ {"F16P", "F16V", "F26L", "F2WV", "F16M", "F16N", "F26H", "F2WQ", "FF58", "FF5C", "FF5F", "FF5H", "FF59", "FF5D", "FF5G", "FF5J"},
  /* MacBookPro11,1 */ {"FH31", "FH35", "FJYK", "FJYL", "FJYM", "FJYR", "FJYY", "FK00", "FMQF", "FMQG", "FN3L", "FN3P", "FN3Q", "FLJJ", "FLJK", "FLJL", "FJYV", "FK01", "FN3K", "FN3M", "FN3N", "FJYT", "FJYW", "FK02", "G3LM", "G3LP", "G3LG", "G3LH", "G3LQ", "GC9Q", "G3LT", "G3M0", "G3LK", "G3LL", "G3LN", "GC9T", "G3LR", "G3LV", "G3LJ", "G3LW", "G3LY", "GC9R"},
  /* MacBookPro11,2 */ {"FJQW", "FJRP", "FJRR", "FJRH", "FJRJ", "FJRN", "FJRC", "FJRV", "FJTQ", "FJT1", "FJTH", "FJTL", "FJRY", "FJTC", "FJTP", "FJR7", "FJR9", "FJRM", "G3M6", "G3M8", "G3M9", "G3M4", "G3M5", "G3M7", "G3MG", "G3MJ", "G3MK"},
  /* MacBookPro11,3 */ {"FP52", "FP58", "FP5C", "FP50", "FP53", "FP54", "G3MH", "G3ML", "G3MM", "G3MG", "G3MJ", "G3MK"},
  /* MacBookPro11,4 */ {"GDQP", "GDQR", "GDQQ", "GDQT", "G7RP", "G7RQ"},
  /* MacBookPro11,5 */ {"GF2C", "GF2D", "GF2F", "GF2G", "GQDF", "GQDG", "GQDH", "GQDJ", "H4P0", "H4P1", "HLG2", "HLG3", "G9LM", "GC9P", "GCQR", "GCQT"},
  /* MacBookPro12,1 */ {"GDVV", "GDVQ", "GDVW", "GDW6", "GDVY", "GDVT", "GDW4", "GDW5", "GDVN", "GDVR", "GDVN", "GDVR", "GQ10", "GDW1", "GDW2", "GDW3"},
  /* MacBookPro13,1 */ {"HMHK", "HMHL", "HMHM", "HMHC", "HMHD", "HMHF", "HMHN", "HMHP", "HMHQ", "HMHG", "HMHH", "HMHJ"},
  /* MacBookPro13,2 */ {"H9W8", "H9WC", "H9WP", "H9WR", "H9W7", "H9W9", "H9WN", "H9WQ", "H1QG", "H1QJ", "H9WK", "H9WM", "H0D3", "H0D5", "H9WD", "H9WG", "H1QF", "H1QH", "H9WJ", "H9WL", "H0F2", "H0F5", "H9X4", "H9X6", "H0D9", "H0DD", "H9WV", "H9WX", "H0DX", "H0F0", "H9X0", "H9X2", "H0F1", "H0F4", "H9X3", "H9X5", "H0D8", "H0DC", "H9WT", "H9WW", "H0DV", "H0DY", "H9WY", "H9X1", "H0FD", "H0FG", "H9XK", "H9XM", "H5F6", "H5F8", "H9X8", "H9XC", "H0F7", "H0F9", "H9XF", "H9XH", "H0FC", "H0FF", "H9XJ", "H9XL", "H5F5", "H5F7", "H9X7", "H9X9", "H0F6", "H0F8", "H9XD", "H9XG"},
  /* MacBookPro13,3 */ {"HCF9", "HCFC", "HCFD", "HCFL", "HCFV", "HCGR", "H54Y", "HCF3", "HCF4", "HCF5", "HCFJ", "HCFN", "HCFQ", "H3PG", "H3PL", "HCFF", "HCFG", "HCFH", "HCFM", "HCFR", "HCFW", "HCFF", "HCFG", "HCFH", "HCFM", "HCFR", "HCFW", "HCDN", "HCDQ", "HCF6", "HCF7", "HCF8", "HCFK", "HCFP", "HCFT", "H551", "HCDK"},
  /* MacBookPro14,1 */ {"HWVP", "HWVR", "HWVV", "HWVN", "HWVQ", "HWVT", "JDDH", "JDDK", "JDDM", "HT4H", "HT4K", "HT4N", "HT4G", "HT4J", "HT4L"},
  /* MacBookPro14,2 */ {"HRPC", "HRPF", "HRPH", "HRR8", "HRRC", "HRRF", "HRNX", "HRP0", "HRP2", "HRQV", "HRQX", "HRR0", "HRP4", "HRP6", "HRP8", "HRR2", "HRR4", "HRR6", "HRP9", "HRPD", "HRPG", "HRR7", "HRR9", "HRRD", "HRNW", "HRNY", "HRP1", "HRQT", "HRQW", "HRQY", "HRP3", "HRP5", "HRP7", "HRR1", "HRR3", "HRR5", "HRQ0", "HRQ2", "HRQ4", "HRRX", "HRT0", "HRT2", "HRPK", "HRPM", "HRPP", "HRRH", "HRRK", "HRRM", "HRPR", "HRPV", "HRPX", "HRRP", "HRRR", "HRRV", "HRPY", "HRQ1", "HRQ3", "HRRW", "HRRY", "HRT1", "HRPJ", "HRPL", "HRPN", "HRRG", "HRRJ", "HRRL", "HRPQ", "HRPT", "HRPW", "HRRN", "HRRQ", "HRRT", "HRQM", "HRQP", "HRQR", "HRTK", "HRTM", "HRTP", "HRQ6", "HRQ8", "HRQC", "HRT4", "HRT6", "HRT8", "HRQF", "HRQH", "HRQK", "HRTC", "HRTF", "HRTH", "HRQL", "HRQN", "HRQQ", "HRTJ", "HRTL", "HRTN", "HRQ5", "HRQ7", "HRQ9", "HRT3", "HRT5", "HRT7", "HRQD", "HRQG", "HRQJ", "HRT9", "HRTD", "HRTG"},
  /* MacBookPro14,3 */ {"J1JH", "J1JJ", "J1JK", "J1JL", "J1JM", "J1JN", "J1JP", "J1JQ", "J1JR", "HRDM", "HRDR", "HRFF", "HRFK", "HRL5", "HRLK", "HYR3", "HYR7", "HYRW", "J1HH", "J1HJ", "J1HK", "J1HL", "J1HM", "J1HN", "J1HP", "J1HQ", "J1HR", "HRDK", "HRDP", "HRFC", "HRFH", "HRL3", "HRLH", "HYR1", "HYR5", "HYRT", "J1JT", "J1JV", "J1JW", "J1JX", "J1JY", "J1K0", "J1K1", "J1K2", "J1K3", "J1J5", "J1J6", "J1J7", "J1J8", "J1J9", "J1JC", "J1JD", "J1JF", "J1JG", "HRDL", "HRDQ", "HRFD", "HRFJ", "HRL4", "HRLJ", "HYR2", "HYR6", "HYRV"},
  /* MacBookPro15,1 */ {"JP4F"},
  /* MacBookPro15,2 */ {"JH4R", "JN1C", "JN1D", "JN1F", "JN1G", "JN1H", "JN1J", "JN1T", "JN1V", "JN1W", "JN1X", "JN1Y", "JN20", "JN21", "JN22", "JN23", "JN0X", "JN0Y", "JN10", "JN11", "JN12", "JN13", "JN1T", "JN1V", "JN1W", "JN1X", "JN1Y", "JN20", "JN21", "JN22", "JN23", "JN1K", "JN1L", "JN1M", "JN1N", "JN1Q", "JN1R", "JN2K", "JN2L", "JN2M", "JN14", "JN15", "JN16", "JN17", "JN18", "JN19", "JN24", "JN25", "JN26", "JN27", "JN28", "JN29", "JN2C", "JN2D", "JN2F", "JJ50", "JJ51", "JJ52", "JJ53", "JJ54", "JJ55", "JJ62", "JJ63", "JJ64", "JH4Q", "JH4T", "JH4W", "JH4Y", "JH50", "JJ5F", "JJ5G", "JJ5H", "JJ5J", "JJ5K", "JJ5L", "JJ5M", "JJ5N", "JJ5P", "JJ56", "JJ57", "JJ58", "JJ59", "JJ5C", "JJ5D", "JJ65", "JJ66", "JJ67", "JH51", "JH52", "JH53", "JH54", "JH55", "JH56", "JJ5Q", "JJ5R", "JJ5T", "JJ5V", "JJ5W", "JJ5X", "JJ5Y", "JJ60", "JJ61"},
  /* MacBookPro2,1  */ {""},
  /* MacBookPro2,2  */ {""},
  /* MacBookPro3,1  */ {""},
  /* MacBookPro4,1  */ {""},
  /* MacBookPro5,1  */ {""},
  /* MacBookPro5,2  */ {""},
  /* MacBookPro5,3  */ {""},
  /* MacBookPro5,4  */ {""},
  /* MacBookPro5,5  */ {""},
  /* MacBookPro6,1  */ {""},
  /* MacBookPro6,2  */ {""},
  /* MacBookPro7,1  */ {""},
  /* MacBookPro8,1  */ {"DM6D", "DM6F", "DM6J", "DM6K", "DM6L", "DM6N", "DM6P", "DM6T", "DMLK", "DMLM", "DMLP", "DMLR", "DRKQ", "DRKR", "DRKT", "DRLN", "DRMH", "DRMJ", "DTFL", "DTFM", "DTFN", "DTFQ", "DTFY", "DTG0", "DM6G", "DM6H", "DM6M", "DM6Q", "DM6R", "DM6V", "DM6W", "DMLL", "DMLN", "DMLQ", "DMLT", "DMLV", "DRKM", "DRKN", "DRKP", "DRKV", "DRMG", "DRMK", "DTFJ", "DTFK", "DTFR", "DTFT", "DTFV", "DTFW", "DTML", "DTMR", "DTMV", "DTMY", "DTN2", "DTN5", "DTMK", "DTMM", "DTMQ", "DTN0", "DTN3", "DTN4"},
  /* MacBookPro8,2  */ {"DMMN", "DMMQ", "DMMR", "DMMW", "DMN4", "DMN6", "DMNN", "DMNP", "DMNQ", "DMNR", "DMNT", "DMNV", "DRMN", "DRMY", "DRN0", "DRN2", "DRN4", "DRN6", "DRP8", "DRPM", "DRPT", "DRPW", "DRQ0", "DRQ3", "DTHH", "DTHR", "DTHW", "DTHY", "DTJ1", "DMML", "DMMM", "DMMV", "DMN1", "DMN3", "DMN5", "DMN7", "DMN8", "DMN9", "DMND", "DMNF", "DMNG", "DRMQ", "DRMT", "DRMV", "DRN1", "DRN7", "DRN8", "DRPC", "DRPK", "DRPL", "DRPQ", "DRPV", "DRQ2", "DTHJ", "DTHN", "DTHQ", "DTHT", "DTHV", "DMMK", "DMMP", "DMMT", "DMMY", "DMN0", "DMN2", "DMNC", "DMNH", "DMNJ", "DMNK", "DMNL", "DMNM", "DRMM", "DRMP", "DRMR", "DRMW", "DRN3", "DRN5", "DRP9", "DRPN", "DRPP", "DRPR", "DRPY", "DRQ1", "DTHK", "DTHL", "DTHM", "DTHP", "DTJ6", "DTWK", "DTWL", "DTWM", "DTWN", "DTWP", "DTWQ", "DTWR", "DTWT", "DTWV", "DTWW", "DTWY", "DTY0", "DYM2", "DYM3", "DYM4", "DYM5", "DYMC", "DYNC", "F16H", "DYN4", "DV36", "DV37", "DV3D", "DV3F", "DV3G", "DV3H", "DV3J", "DV3M", "DV3P", "DV3V", "DV3Y", "DV40", "DYM6", "DYM8", "DYM9", "DYMF", "DYMJ", "DV32", "DV34", "DV38", "DV39"},
  /* MacBookPro8,3  */ {"DM5K", "DM5L", "DM5N", "DM5Q", "DM5R", "DM5W", "DMM0", "DMM1", "DMM5", "DMM9", "DMMC", "DMMD", "DM5J", "DM5M", "DM5P", "DM5T", "DM5V", "DM5Y", "DMM2", "DMM3", "DMM4", "DMM6", "DMM7", "DMM8", "DTYV", "DTYW", "DV01", "DV02", "DV03", "DV06", "DV07", "DV0C", "DV0H", "DV0J", "DV0K", "DV0M", "DYL5", "DYL7", "DYLC", "DYLF", "DYLG", "DTYT", "DTYY", "DV00", "DV04", "DV05", "DV08", "DV09", "DV0D", "DV0F", "DV0G", "DV0L", "DV0N", "DYL4", "DYL6", "DYL8", "DYL9", "DYLD"},
  /* MacBookPro9,1  */ {"F327", "F32C", "F3JG", "F3JK", "F324", "F325", "F3JH", "F3JJ", "F328", "F329", "F3JF", "F3JL"},
  /* MacBookPro9,2  */ {"F1YJ", "F1YL", "F1YM", "F1YG", "F1YH", "F1YK"},
  /* MacPro1,1      */ {""},
  /* MacPro2,1      */ {""},
  /* MacPro3,1      */ {""},
  /* MacPro4,1      */ {""},
  /* MacPro5,1      */ {""},
  /* MacPro6,1      */ {"FHDD", "FNN1"},
  /* Macmini1,1     */ {""},
  /* Macmini2,1     */ {""},
  /* Macmini3,1     */ {""},
  /* Macmini4,1     */ {"DC2D", "DC40", "DC5G", "DC6Y"},
  /* Macmini5,1     */ {"DKP2"},
  /* Macmini5,2     */ {"DK22", "DN77"},
  /* Macmini5,3     */ {"DHDN"},
  /* Macmini6,1     */ {"F1HC", "DVF8"},
  /* Macmini6,2     */ {"DVF9", "F1H8", "F1G2", "F1H9"},
  /* Macmini7,1     */ {"G0MC", "FWY2", "FYRD", "G3N7", "G0MH", "G0MJ", "G3ND", "G0MK", "FYRF", "G0MF", "G3NC", "FYRK", "FYRH", "FYRJ", "G3N9", "G0MM", "G0MN", "G0MP", "G3N8"},
  /* Macmini8,1     */ {"KXPG", "KXVT", "KXW5", "KXQJ", "KXQW", "KXX7", "KXRY", "KXV3", "KXVG", "KXQ5", "KXYC", "KXWJ", "KXWW"},
  /* Xserve1,1      */ {"V1C"},
  /* Xserve2,1      */ {"OVE", "XZU"},
  /* Xserve3,1      */ {"63C", "1PH"},
  /* iMac10,1       */ {""},
  /* iMac11,1       */ {""},
  /* iMac11,2       */ {""},
  /* iMac11,3       */ {""},
  /* iMac12,1       */ {"DJWK", "DM66", "DNJK", "DP0H", "DKG1", "DM65", "DNJJ", "DKG2", "DM67", "DNJL", "DP0K", "DP00"},
  /* iMac12,2       */ {"DJWM", "DMT3", "DMT5", "DJWN", "DM69", "DJWP", "DM6C"},
  /* iMac13,1       */ {"DYWF", "F117", "F502", "F505", "F9GY", "F9H0", "F9H1", "F9H2", "FF4G", "FF4H", "FF4J", "FF4K", "FF4L"},
  /* iMac13,2       */ {"F2FR", "F653", "F49P", "F651", "F49R", "F652", "DYW3", "F64V", "F0V5", "F64W"},
  /* iMac13,3       */ {"F8GR"},
  /* iMac14,1       */ {"FM59"},
  /* iMac14,2       */ {"F8YL", "FCTC", "FC3F", "FC3J", "FN7H", "FN71", "FN72", "FN3W"},
  /* iMac14,3       */ {"F9RR", "F9T5", "F9RW", "F9T3"},
  /* iMac14,4       */ {"G36D", "G36G", "G3W2", "FT57", "FT5F", "G3W3"},
  /* iMac15,1       */ {"G2Y7", "G2Y8", "GG3L", "GG3N", "G2QD", "G2QF", "GG3T", "GG3W", "FT04", "FW6K", "GG3K", "GG3M", "FW29", "FW2C", "GG3Q", "GG3V", "FQY8", "FTPF"},
  /* iMac16,1       */ {"GH34", "GQ6K", "GQ6L", "GVYR", "GDF9", "GQ6F", "GQ6G", "GVYQ", "GH32", "GH36", "GQ6H", "GQ6J", "GVYV", "GDF7", "GDF8", "GQ6C", "GQ6D", "GVYT", "GPX5", "GPX6", "GPX7", "GPXC", "GPXD", "GPXF", "GPX3", "GPX4", "GXMK", "GPX8", "GPX9", "GXML"},
  /* iMac16,2       */ {"GQRY", "GQT0", "GQT1", "GPXJ", "GPXK", "GPXL", "GQRW", "GQRX", "GXMM", "GPXG", "GPXH", "GXMN", "GQT4", "GQT5", "GQT6", "GPXP", "GPXQ", "GPXR", "GQT2", "GQT3", "GXMP", "GPXM", "GPXN", "GXMQ"},
  /* iMac17,1       */ {"GPF7", "GPF8", "GPF3", "GPF4", "GTL1", "GTL2", "GPJ8", "GPJD", "GPDY", "GPF0", "GTL3", "GTL4", "GPJF", "GPJH", "GPJ9", "GPJJ", "GPJC", "GPJG"},
  /* iMac18,1       */ {"H69F", "H668"},
  /* iMac18,2       */ {"J0DX", "J0DY", "J0F0", "J0F1", "HNWJ", "HNWK", "J0RY", "J0T1", "HNWL", "HNWM", "HNWN", "HNWP"},
  /* iMac18,3       */ {"J0PG", "J0PH", "J0PJ", "J0PC", "J0PD", "J0PF", "HX77", "HX78", "HX79", "HX7C", "HX7D", "HX7F", "HNL6", "HNL7", "HNL8"},
  /* iMac19,1       */ {"LNV9", "KDP0"},
  /* iMac19,2       */ {"KGQG"},
  /* iMac4,1        */ {""},
  /* iMac4,2        */ {""},
  /* iMac5,1        */ {""},
  /* iMac5,2        */ {""},
  /* iMac6,1        */ {""},
  /* iMac7,1        */ {""},
  /* iMac8,1        */ {""},
  /* iMac9,1        */ {""},
  /* iMacPro1,1     */ {"JG36", "JG3C", "JG3D", "JG38", "JG39", "JML3", "JMPY", "JMQ0", "JML4", "JMQ1", "JMQ2", "J806", "J807", "J808", "J80H", "J80J", "J80M", "J803", "J804", "J805", "J809", "J80D", "J80F"},
};

#define APPLE_MODEL_YEAR_MAX 3
static uint32_t AppleModelYear[][APPLE_MODEL_YEAR_MAX] = {
  /* MacBook1,1     */ {2006},
  /* MacBook10,1    */ {2017},
  /* MacBook2,1     */ {2006, 2007},
  /* MacBook3,1     */ {2007, 2008},
  /* MacBook4,1     */ {2008, 2009},
  /* MacBook5,1     */ {2008, 2009},
  /* MacBook5,2     */ {2009},
  /* MacBook6,1     */ {2009, 2010},
  /* MacBook7,1     */ {2010},
  /* MacBook8,1     */ {2015, 2016},
  /* MacBook9,1     */ {2016, 2017},
  /* MacBookAir1,1  */ {2007, 2008, 2009},
  /* MacBookAir2,1  */ {2008, 2009},
  /* MacBookAir3,1  */ {2011},
  /* MacBookAir3,2  */ {2011},
  /* MacBookAir4,1  */ {2011, 2012},
  /* MacBookAir4,2  */ {2011, 2012},
  /* MacBookAir5,1  */ {2012, 2013},
  /* MacBookAir5,2  */ {2012, 2013},
  /* MacBookAir6,1  */ {2013, 2014},
  /* MacBookAir6,2  */ {2013, 2014},
  /* MacBookAir7,1  */ {2015, 2016},
  /* MacBookAir7,2  */ {2015, 2016, 2017},
  /* MacBookAir8,1  */ {2018},
  /* MacBookPro1,1  */ {2006},
  /* MacBookPro1,2  */ {2006},
  /* MacBookPro10,1 */ {2012, 2013},
  /* MacBookPro10,2 */ {2012, 2013},
  /* MacBookPro11,1 */ {2013, 2014},
  /* MacBookPro11,2 */ {2013, 2014},
  /* MacBookPro11,3 */ {2013, 2014},
  /* MacBookPro11,4 */ {2015},
  /* MacBookPro11,5 */ {2015, 2016},
  /* MacBookPro12,1 */ {2015},
  /* MacBookPro13,1 */ {2016},
  /* MacBookPro13,2 */ {2016, 2017},
  /* MacBookPro13,3 */ {2016},
  /* MacBookPro14,1 */ {2017},
  /* MacBookPro14,2 */ {2017},
  /* MacBookPro14,3 */ {2017, 2018},
  /* MacBookPro15,1 */ {2018},
  /* MacBookPro15,2 */ {2018},
  /* MacBookPro2,1  */ {2006, 2007},
  /* MacBookPro2,2  */ {2006, 2007},
  /* MacBookPro3,1  */ {2007, 2008},
  /* MacBookPro4,1  */ {2007, 2008, 2009},
  /* MacBookPro5,1  */ {2008, 2009},
  /* MacBookPro5,2  */ {2009},
  /* MacBookPro5,3  */ {2009, 2010},
  /* MacBookPro5,4  */ {2009, 2010},
  /* MacBookPro5,5  */ {2009, 2010},
  /* MacBookPro6,1  */ {2010},
  /* MacBookPro6,2  */ {2010},
  /* MacBookPro7,1  */ {2010},
  /* MacBookPro8,1  */ {2011, 2012},
  /* MacBookPro8,2  */ {2011, 2012},
  /* MacBookPro8,3  */ {2011, 2012},
  /* MacBookPro9,1  */ {2012, 2013},
  /* MacBookPro9,2  */ {2012, 2013, 2014},
  /* MacPro1,1      */ {2006, 2007, 2008},
  /* MacPro2,1      */ {2007, 2008},
  /* MacPro3,1      */ {2008, 2009},
  /* MacPro4,1      */ {2009},
  /* MacPro5,1      */ {2010, 2011, 2012},
  /* MacPro6,1      */ {2013},
  /* Macmini1,1     */ {2006},
  /* Macmini2,1     */ {2007, 2008, 2009},
  /* Macmini3,1     */ {2009},
  /* Macmini4,1     */ {2011},
  /* Macmini5,1     */ {2011, 2012},
  /* Macmini5,2     */ {2011, 2012},
  /* Macmini5,3     */ {2011, 2012},
  /* Macmini6,1     */ {2012, 2013, 2014},
  /* Macmini6,2     */ {2012, 2013, 2014},
  /* Macmini7,1     */ {2014},
  /* Macmini8,1     */ {2018},
  /* Xserve1,1      */ {2006, 2007, 2008},
  /* Xserve2,1      */ {2008, 2009},
  /* Xserve3,1      */ {2009},
  /* iMac10,1       */ {2009, 2010},
  /* iMac11,1       */ {2009, 2010},
  /* iMac11,2       */ {2010},
  /* iMac11,3       */ {2010},
  /* iMac12,1       */ {2011, 2012},
  /* iMac12,2       */ {2011, 2012},
  /* iMac13,1       */ {2012},
  /* iMac13,2       */ {2012, 2013},
  /* iMac13,3       */ {2013},
  /* iMac14,1       */ {2013, 2014, 2015},
  /* iMac14,2       */ {2013, 2014, 2015},
  /* iMac14,3       */ {2014, 2015},
  /* iMac14,4       */ {2014, 2015},
  /* iMac15,1       */ {2014, 2015},
  /* iMac16,1       */ {2015, 2016, 2017},
  /* iMac16,2       */ {2015, 2016, 2017},
  /* iMac17,1       */ {2015, 2016, 2017},
  /* iMac18,1       */ {2017},
  /* iMac18,2       */ {2017},
  /* iMac18,3       */ {2017, 2018},
  /* iMac19,1       */ {2019},
  /* iMac19,2       */ {2019},
  /* iMac4,1        */ {2006},
  /* iMac4,2        */ {2006},
  /* iMac5,1        */ {2006, 2007},
  /* iMac5,2        */ {2006, 2007},
  /* iMac6,1        */ {2006, 2007},
  /* iMac7,1        */ {2007, 2008},
  /* iMac8,1        */ {2008},
  /* iMac9,1        */ {2009},
  /* iMacPro1,1     */ {2017},
};

static uint32_t ApplePreferredModelYear[] = {
  /* MacBook1,1     */ 0,
  /* MacBook10,1    */ 0,
  /* MacBook2,1     */ 0,
  /* MacBook3,1     */ 0,
  /* MacBook4,1     */ 0,
  /* MacBook5,1     */ 0,
  /* MacBook5,2     */ 0,
  /* MacBook6,1     */ 0,
  /* MacBook7,1     */ 0,
  /* MacBook8,1     */ 0,
  /* MacBook9,1     */ 0,
  /* MacBookAir1,1  */ 0,
  /* MacBookAir2,1  */ 0,
  /* MacBookAir3,1  */ 0,
  /* MacBookAir3,2  */ 0,
  /* MacBookAir4,1  */ 0,
  /* MacBookAir4,2  */ 0,
  /* MacBookAir5,1  */ 0,
  /* MacBookAir5,2  */ 0,
  /* MacBookAir6,1  */ 0,
  /* MacBookAir6,2  */ 0,
  /* MacBookAir7,1  */ 0,
  /* MacBookAir7,2  */ 0,
  /* MacBookAir8,1  */ 0,
  /* MacBookPro1,1  */ 0,
  /* MacBookPro1,2  */ 0,
  /* MacBookPro10,1 */ 0,
  /* MacBookPro10,2 */ 0,
  /* MacBookPro11,1 */ 0,
  /* MacBookPro11,2 */ 0,
  /* MacBookPro11,3 */ 0,
  /* MacBookPro11,4 */ 0,
  /* MacBookPro11,5 */ 0,
  /* MacBookPro12,1 */ 0,
  /* MacBookPro13,1 */ 0,
  /* MacBookPro13,2 */ 0,
  /* MacBookPro13,3 */ 0,
  /* MacBookPro14,1 */ 0,
  /* MacBookPro14,2 */ 0,
  /* MacBookPro14,3 */ 0,
  /* MacBookPro15,1 */ 0,
  /* MacBookPro15,2 */ 0,
  /* MacBookPro2,1  */ 0,
  /* MacBookPro2,2  */ 0,
  /* MacBookPro3,1  */ 0,
  /* MacBookPro4,1  */ 0,
  /* MacBookPro5,1  */ 0,
  /* MacBookPro5,2  */ 0,
  /* MacBookPro5,3  */ 0,
  /* MacBookPro5,4  */ 0,
  /* MacBookPro5,5  */ 0,
  /* MacBookPro6,1  */ 0,
  /* MacBookPro6,2  */ 0,
  /* MacBookPro7,1  */ 0,
  /* MacBookPro8,1  */ 0,
  /* MacBookPro8,2  */ 0,
  /* MacBookPro8,3  */ 0,
  /* MacBookPro9,1  */ 0,
  /* MacBookPro9,2  */ 0,
  /* MacPro1,1      */ 0,
  /* MacPro2,1      */ 0,
  /* MacPro3,1      */ 0,
  /* MacPro4,1      */ 0,
  /* MacPro5,1      */ 2011,
  /* MacPro6,1      */ 0,
  /* Macmini1,1     */ 0,
  /* Macmini2,1     */ 0,
  /* Macmini3,1     */ 0,
  /* Macmini4,1     */ 0,
  /* Macmini5,1     */ 0,
  /* Macmini5,2     */ 0,
  /* Macmini5,3     */ 0,
  /* Macmini6,1     */ 0,
  /* Macmini6,2     */ 0,
  /* Macmini7,1     */ 0,
  /* Macmini8,1     */ 0,
  /* Xserve1,1      */ 0,
  /* Xserve2,1      */ 0,
  /* Xserve3,1      */ 0,
  /* iMac10,1       */ 0,
  /* iMac11,1       */ 0,
  /* iMac11,2       */ 0,
  /* iMac11,3       */ 0,
  /* iMac12,1       */ 0,
  /* iMac12,2       */ 0,
  /* iMac13,1       */ 0,
  /* iMac13,2       */ 0,
  /* iMac13,3       */ 0,
  /* iMac14,1       */ 0,
  /* iMac14,2       */ 0,
  /* iMac14,3       */ 0,
  /* iMac14,4       */ 0,
  /* iMac15,1       */ 0,
  /* iMac16,1       */ 0,
  /* iMac16,2       */ 0,
  /* iMac17,1       */ 0,
  /* iMac18,1       */ 0,
  /* iMac18,2       */ 0,
  /* iMac18,3       */ 0,
  /* iMac19,1       */ 0,
  /* iMac19,2       */ 0,
  /* iMac4,1        */ 0,
  /* iMac4,2        */ 0,
  /* iMac5,1        */ 0,
  /* iMac5,2        */ 0,
  /* iMac6,1        */ 0,
  /* iMac7,1        */ 0,
  /* iMac8,1        */ 0,
  /* iMac9,1        */ 0,
  /* iMacPro1,1     */ 0,
};

#endif // GENSERIAL_MODELINFO_AUTOGEN_H
